runtime: python27
threadsafe: true

handlers:
  - url: /static
    static_dir: app/static/css

  - url: /static
    static_dir: app/static/image

  - url: /.*
    script: app.flask_app.app

libraries:
  - name: ssl
    version: latest